application:


  cron:
    crawler-cron: "0 0 9,23 * * ? "

  crawler:
    path: E:/123/chromedriver.exe


  server-chan:
    server: https://sc.ftqq.com/
    secret-key: 123
    debug: false
    proxy: false

  tencent-cos:
    base-url: 123
    secret-id: 123
    secret-key: 123
    debug: false